adb push 0.bmp /sdcard
adb push 1.bmp /sdcard
adb push 2.bmp /sdcard
adb push 3.bmp /sdcard
adb push 4.bmp /sdcard
adb push 5.bmp /sdcard
adb push 6.bmp /sdcard
adb push 7.bmp /sdcard
adb push 8.bmp /sdcard
adb push 9.bmp /sdcard
adb push f1.bmp /sdcard
adb push f2.bmp /sdcard
adb push f3.bmp /sdcard
adb push enter.bmp /sdcard
adb push cancel.bmp /sdcard
adb push backspace.bmp /sdcard
